### ISSUE TITLE
error when latitude or longitude is integer

### ISSUE THREAD

**Issue by naser13** [200Puls/darksky-forecast-api#12]
Cannot construct instance of `tk.plogitech.darksky.forecast.model.Longitude` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (50)

**Comment by twonggg** [comment]
`ForecastRequest request = new ForecastRequestBuilder().key(new APIKey(DARK_SKY_API_KEY)).location(new GeoCoordinates(new Longitude(22.1234), new Latitude(41.0))).time(startTime.toInstant()).language(Language.en).units(Units.si).exclude(Block.minutely, Block.hourly, Block.daily).build();`

The JSON response says 

`{
  "latitude": 41,
  "longitude": 22.000000715255737,
  "timezone": "Europe/Athens",
  ...
}`

The 41 is recognized as Number value.

**Comment by twonggg** [comment]
`ForecastRequest request = new ForecastRequestBuilder().key(new APIKey(DARK_SKY_API_KEY)).location(new GeoCoordinates(new Longitude(22.1234), new Latitude(41.0))).time(startTime.toInstant()).language(Language.en).units(Units.si).exclude(Block.minutely, Block.hourly, Block.daily).build();`

The JSON response says 

`{
  "latitude": 41,
  "longitude": 22.1234,
  "timezone": "Europe/Athens",
  ...
}`

The 41 is recognized as Number value.

**Comment by 200Puls** [comment]
Hi @twonggg and @naser13.

I just pushed 1.3.1 with a fix to maven (might take a couple hours). Let me know if its working for you.

**Comment by twonggg** [comment]
It works perfectly, thank you!
