### ISSUE TITLE
latitude and longitude sometimes appears in request URL in scientific notation resulting in a 400 response code

### ISSUE THREAD

**Issue by shanusmcshan** [200Puls/darksky-forecast-api#18]
for example a longitude supplied as a double of -0.000066 appears in the get URL as **-6.6E-5** resulting in HTTP response code: 400

**Comment by 200Puls** [comment]
Hey thanks for the report. I could reproduce the issue and fixed it with the latest release. it will take a few hours for maven central to be in sync.
