### ISSUE TITLE
Decimal formatting

### ISSUE THREAD

**Issue by ProgrammIt** [200Puls/darksky-forecast-api#27]
There is a problem with the formatting of decimal numbers. In countries where the notation differs from something like 5.75 the url is not formatted correctly.

Example code from read.me at "https://github.com/200Puls/darksky-forecast-api":

ForecastRequest request = new ForecastRequestBuilder()
                .key(new APIKey("key"))
                .location(new GeoCoordinates(new Longitude(13.377704), new Latitude(52.516275))).build();

        DarkSkyJacksonClient client = new DarkSkyJacksonClient();
        //Forecast forecast = client.forecast(request);

        /* I added this to see what's happening -> */ System.out.println(request);

/*System.out.println("forecast " + forecast);
        System.out.println("forecast " + forecast.getCurrently().getTemperature());*/

**You get the following by the "System.out.println(request);" statement:**
ForecastRequest{url=https://api.darksky.net/forecast/key/52,516275,13,377704?lang=de&units=si}

**But it should be something like this:** 
ForecastRequest{url=https://api.darksky.net/forecast/key/52.516275,13.377704?lang=de&units=si}

If you stick with commas you will get an http-response-code 400 "bad request". At least you are in a country like germany.

I tried to request data with "https://api.darksky.net/forecast/key/52.516275,13.377704?lang=de&units=si" and it worked pretty well.

Apart from this bug, you made an awesome job. This is a great library.

**Comment by 200Puls** [comment]
Hi,
thanks for reporting. This should be fixed with release 2.1.0.

**Comment by ProgrammIt** [comment]
No problem. Thanks for fixing. 😉
