### ISSUE TITLE
set timeout for request

### ISSUE THREAD

**Issue by shaharl** [200Puls/darksky-forecast-api#8]
Please enable to set the timeout for the request.

**Comment by 200Puls** [comment]
Hi,
timeouts are useful and should be easy to integrate. I will try to find the time this week.

**Comment by 200Puls** [comment]
Hi i just published 1.2.0 with this change. Hope it helps.

**Comment by shaharl** [comment]
Thanks!

I use jdk8, so I have a problem with `toMillisPart `

https://github.com/200Puls/darksky-forecast-api/blob/master/darksky-forecast-api/src/main/java/tk/plogitech/darksky/forecast/DarkSkyClient.java#L102

**Comment by 200Puls** [comment]
Sorry, that was a typo / autocomplete bug. I just pushed 1.2.1. Might take a few hours till its seeable on maven.
